国・都道府県・河川名で取得するデータを選択できるよう修正
Noah0x0/lambda-rainFallAPI pull request #5
Opened 2017-08-16 12:37 UTC by runble1

Endpoint : 
/production/water-level?country="japana"&prefectures="tokyo"&river="arakawa"
1. country : 国名
2. prefectures : 都道府県
3. river : 河川名

2017-08-16 14:39 UTC, mesh1nek0x0 requested changes
質問しましたー！

2017-08-16 14:39 UTC, mesh1neko commented on lambda_function.py
> +    list = client.list_objects(
ASK
waterLevelと一緒なんですが、bucket内全取得になりそうなので、ある程度日時で絞ったほうがよいかとおもいますー！ファイルはUTCで作られているので、UTCで絞り込めばかなり絞り込めるはず...

2017-08-16 14:39 UTC, mesh1neko commented on lambda_function.py
> +        target_key = get_latest_keyname(prefix)
ASK
ここもwaterLevelと一緒ですが、target_keyが空の場合はありえますか？
その場合、次の処理は大丈夫でしょうか...

2017-08-16 15:18 UTC, mesh1nek0x0 approved these changes
+1

2017-08-16 15:20 UTC, mesh1neko commented
[![LGTM](http://lgtm.in/p/QuenzQ7jq)](http://lgtm.in/i/QuenzQ7jq)

2017-08-18 14:20 UTC, runble1 commented
以下2つを対応しました。
1. 取得するS3の一覧を年月で絞る対応
2. 無効なURLを指定された際の 400 BadRequest を返却

2017-08-19 05:53 UTC, mafuyuk commented on README.md
> +Endpoint : /production/rain-fall?country="japan"&prefectures="tokyo"&river="arakawa"
path違います

2017-08-19 05:56 UTC, mesh1nek0x0 approved these changes
+1

2017-08-19 06:20 UTC, merged